### PR TITLE
Misc cleanup

### PR DESCRIPTION
**Pull request by hugelgupf**
Based on #225. Some random stuff.

### CODE REVIEW

**Comment by hugelgupf** [comment]
This is where https://github.com/rtr7/router7/pull/19 comes in.

**Comment by insomniacslk** [comment]
Looks good to me, thanks! Another excellent improvement.
Once the OptVersion build failure is addressed this can be merged

**Comment by pmazzini** [comment]
@insomniacslk I wanted to go ahead with the merge to avoid blocking @hugelgupf but I can't since this PR breaks the `router7` build, which will be fixed with https://github.com/rtr7/router7/pull/19. Do I have permission to merge it even if the travis build fails?

**Comment by hugelgupf** [comment]
You're gonna have to - rtr7 doesnt use vendor or modules. And I can't submit both PRs together as one. And this dhcp one has to come first.

**Comment by insomniacslk** [comment]
as @hugelgupf said - this PR has to be merged first, then @stapelberg will have to merge https://github.com/rtr7/router7/pull/19

**Pull request merged**
