### PR TITLE
Adding Arista port-channel naming, correct line index

### PR DESCRIPTION
**Pull request by RobelK1**
This change will add interface Arista port-channel support for DHCP replay function

### CODE REVIEW

**Comment by pmazzini** [comment]
Please add unit tests with example circuits in `parse_circuitid_test.go`.

**Comment by pmazzini** [comment]
Please sign the commit:

```
To add your Signed-off-by line to every commit in this branch:

Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
In your local branch, run: git rebase HEAD~1 --signoff
Force push your changes to overwrite the branch: git push --force-with-lease origin master
```

**Review by RobelK1 — COMMENTED** [review]
Added changed as per review

**Review by RobelK1 — COMMENTED** [review]
rebaseds as per review and signed-off previous commits too

**Comment by pmazzini** [comment]
DCO is failing:

https://github.com/insomniacslk/dhcp/pull/500/checks?check_run_id=12553255492

**Pull request closed without merging**
