### PR TITLE
Adding DHCPv6 Option 17 - Vendor Options

### PR DESCRIPTION
**Pull request by gorhamc**
Adding option code for DHVPv6 Option 17 based on https://tools.ietf.org/html/rfc3315#section-22.17

I'm  not modifying the options.go ParseOptions function just yet. The vendor I need this for isn't currently following the RFC apparently. I will add this option into ParseOptions when they abide by RFC, hopefully very soon. For now this is reserved for future use.

### CODE REVIEW

**Comment by insomniacslk** [comment]
Thanks for your contribution!
To start with, can you please address the linter warnings and increase the test coverage so that CodeCov is happy?

**Comment by insomniacslk** [comment]
What happens exactly if you enable this option in `options.go`? Will it panic or return some other error?

**Comment by gorhamc** [comment]
If I enable in options.go, in my specific usecase, the packet data ends up with truncated data because the packet is parsed per the RFC.  My test vendor is not sending the Enterprise-ID currently, so their data in the vendor-specific-information option field ends up incomplete because the first 4-bytes are parsed as Enterprise-ID. If that makes sense. I attached a screenshot of a packet capture illustrating my issue.

screen shot 2018-07-26 at 2 40 40 pm

**Comment by gorhamc** [comment]
sorry for all the extra commits. I'm not a heavy Github user.

**Comment by gorhamc** [comment]
Not sure why the build is saying OPTION_VENDOR_OPTS is undefined. It exists in option_types.go

OPTION_VENDOR_OPTS                 OptionCode = 17

**Comment by pmazzini** [comment]
> What happens exactly if you enable this option in `options.go`? Will it panic or return some other error?

@insomniacslk I think the whole packet parsing will fail, so I wouldn't add it there.

@gorhamc Thanks for your contribution.

> Not sure why the build is saying OPTION_VENDOR_OPTS is undefined. It exists in option_types.go

It was recently changed to `OptionVendorOpts` in PR #106.

**Comment by gorhamc** [comment]
ugh, looks like this picked up A LOT of changes that aren't mine. sigh. I clearly suck at github.

**Comment by gorhamc** [comment]
should we just cancel/close this PR so I can start over with less fail?

**Comment by insomniacslk** [comment]
Sure, just reference this PR so we keep track of the conversation 

On 10 August 2018 22:20:24 GMT+01:00, gorhamc <notifications@github.com> wrote:
>should we just cancel/close this PR so I can start over with less fail?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/insomniacslk/dhcp/pull/110#issuecomment-412209694

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request closed without merging**
