### PR TITLE
Add partial (client) binding support for BSD

### PR DESCRIPTION
**Pull request by dmgk**
Related to #240

### CODE REVIEW

**Comment by pmazzini** [comment]
@dmgk Thanks for your contribution! Doesn't it need a build constraint / build tag?

**Comment by dmgk** [comment]
@pmazzini It does have one, currently constraining the build to freebsd, openbsd and netbsd only:  https://github.com/insomniacslk/dhcp/pull/260/files#diff-e78aed4e493232b381170e9512c08c72R1

**Comment by pmazzini** [comment]
@dmgk Would you mind closing and reopening the PR (it is just two clicks) to trigger a new travis build?

**Comment by pmazzini** [comment]
@dmgk Thanks for your contribution!

**Comment by dmgk** [comment]
@pmazzini Thanks for merging!

**Pull request merged**
