### PR TITLE
go.mod: bump uio dep to move to unified native endian package

### PR DESCRIPTION
**Pull request by bradfitz**
To pick up this change:
https://github.com/u-root/uio/commit/c3537552635f86c59cf805d1755fa656a2073922

Updates golang/go#57237

### CODE REVIEW

**Comment by bradfitz** [comment]
cc @hugelgupf

**Review by hugelgupf — DISMISSED** [review]

**Comment by hugelgupf** [comment]
I... don't know why the DCO check isn't doing anything. (But I don't have admin here so I can't override.) Could you push an empty commit or something to retrigger @bradfitz ?

**Comment by bradfitz** [comment]
@hugelgupf, okay, re-pushed (after rebasing to latest master)

**Comment by bradfitz** [comment]
DCO seems happy now. I also had never seen DCO bot get stuck like that before.

**Comment by bradfitz** [comment]
@hugelgupf, whoops, you'd approved but then I clicked the "re-request approval" button out of habit.

**Review by hugelgupf — APPROVED** [review]

**Pull request merged**
