### PR TITLE
Fix nclient4 build

### PR DESCRIPTION
**Pull request by hugelgupf**
cc @mfischer

### CODE REVIEW

**Comment by hugelgupf** [comment]
Erm, @insomniacslk, Travis appears to not be a check anymore?

**Comment by hugelgupf** [comment]
Oh crazy. The open source plans were disabled by Travis at the end of 2020. We need a new CI provider.

Mind if I set up CircleCI? I'll just copy the setup we have in all our other repos.

**Comment by insomniacslk** [comment]
hey @hugelgupf , I don't know what happened to Travis-CI, but I'll replace this with GitHub Actions as I did on other projects

**Comment by insomniacslk** [comment]
> Oh crazy. The open source plans were disabled by Travis at the end of 2020. We need a new CI provider.
> 
> Mind if I set up CircleCI? I'll just copy the setup we have in all our other repos.

if you have a strong argument for CircleCI over GitHub Actions, let's go with it. I am personally more familiar with GitHub Actions but I don't mind if you prefer CircleCI and want to do that

**Comment by hugelgupf** [comment]
I don't know how to use Github Actions, haha, but I don't care either way -- set it up the way you like. 

Let me remove the travis commit from this PR so I can get nclient4 to build again

**Comment by insomniacslk** [comment]
alright, give me a few minutes to put up a PR

**Review by pmazzini — APPROVED** [review]

**Comment by hugelgupf** [comment]
thanks andrea

**Comment by insomniacslk** [comment]
this made me realize that we also need license headers in our CI

**Comment by insomniacslk** [comment]
Draft PR at https://github.com/insomniacslk/dhcp/pull/414

**Pull request merged**
