### PR TITLE
dhcpv6: simplify boot file URL

### PR DESCRIPTION
**Pull request by hugelgupf**
Signed-off-by: Chris Koch <chrisko@google.com>

### CODE REVIEW

**Comment by hugelgupf** [comment]
prioritize this, the other 2 PRs don't matter

**Comment by insomniacslk** [comment]
LGTM. @pmazzini we should probably adjust a few things after importing this

**Comment by insomniacslk** [comment]
@hugelgupf can you rebase this please?

**Comment by pmazzini** [comment]
> LGTM. @pmazzini we should probably adjust a few things after importing this

Yes.

**Pull request merged**
