### PR TITLE
[dhcpv6] More getters for MessageOptions

### PR DESCRIPTION
**Pull request by insomniacslk**
Added IAAddress, OneIAAddress, UserClasses, VendorOpts, and changed
Options to MessageOptions in IA_NA and IA_Address options.

Signed-off-by: Andrea Barberio <insomniac@slackware.it>

### CODE REVIEW

**Comment by insomniacslk** [comment]
This will help fixing https://github.com/facebookincubator/dhcplb/issues/30

**Comment by insomniacslk** [comment]
....I missed that

**Comment by hugelgupf** [comment]
The options are also intentionally grouped -- 

> When using the library, I don't know if for example the FQDN option is supposed to be in a DHCPv6 message, in a relay message, in an IANA or an IATA. Where can it appear, which places do I have to check? The option groups are supposed to answer that question.

(From previous PR)

**Comment by insomniacslk** [comment]
alright I'll close this one and review #349

**Comment by hugelgupf** [comment]
I think the VendorOpts and UserClass are still valid - I missed those earlier

**Comment by insomniacslk** [comment]
can you please rebase and resolve the conflicts on #349 ?

**Comment by insomniacslk** [comment]
removed changes overlapping with #349

**Comment by hugelgupf** [comment]
On it in a few

**Comment by insomniacslk** [comment]
router7 fixes in related PR, merging this

**Pull request merged**
