### PR TITLE
Adding RemoteID option while creating a Relayed Encapsulated Packet 

### PR DESCRIPTION
**Pull request by akshaynawale**
The dhcpv6 client was not updating the Remote ID option to the outer encapsulated packet, for SimulateRelay Flag. This was causing problems in testing dhcp requests with Remote ID. As Remote ID is set by the Relay Agent so it should be present at the outer encapsulated packet. This change will copy the inner message's Remote ID option if present, to the outer encapsulated message.

Tested by running unit tests. 
```
go test 
2019/05/07 15:58:22 DNS OptDNSRecursiveNameServer{nameservers=[fe80::1 fe80::2]}
PASS
ok      _/home/navale/go/src/github.com/akshaynawale/dhcp/dhcpv6        0.009s
```

### CODE REVIEW

**Comment by insomniacslk** [comment]
Thanks @akshaynawale ! Can you please amend the commit to include the Signed-Off-By footer? `git commit --amend -s` should suffice

**Comment by insomniacslk** [comment]
The CI is also failing<;
```
dhcpv6/client6/client.go:95:3: undefined: encapPacket
dhcpv6/client6/client.go:101:4: undefined: encapPacket
dhcpv6/client6/client.go:103:12: undefined: encapPacket
```

**Comment by akshaynawale** [comment]
Yes forgot to initialize the encapPacket. I have fixed it now. I also tried to fix the signoff message but tje DCO is stilling failing. I dont know if I am doing anything wrong.

**Comment by akshaynawale** [comment]
Signed off all the commits.

**Comment by pmazzini** [comment]
> As Remote ID is set by the Relay Agent so it should be present at the outer encapsulated packet.

I am not following this. In this PR you are copying the Remote ID. When simulating a relay, who populates the Remote ID?

**Comment by pmazzini** [comment]
I see the issue now. You are probably using a modifier to add a remote id but it is being added to the `Message` and not to the `Relay`, and with this PR you are copying it over. However, it doesn't make sense to add a remote id to a dhcpv6 `Message`.

I don't see a nice solution for this. How about adding the remote id to the client struct, similar to what we are doing with the `SimulateRelay` bool?

**Comment by akshaynawale** [comment]
Make sense Pablo. I will update this.

**Comment by akshaynawale** [comment]
Added a field in client called RelayOptions which is dhcpv6.Options and can be used to pass options we need to add to the relay message.

**Comment by pmazzini** [comment]
Thanks!

**Pull request merged**
