### PR TITLE
remove deprecated functions

### PR DESCRIPTION
**Pull request by pmazzini**

### CODE REVIEW

**Comment by insomniacslk** [comment]
I am not convinced by this change, as discussed on https://github.com/insomniacslk/dhcp/pull/181 . Let's continue the conversation there so we keep it in one thread

**Comment by pmazzini** [comment]
Abandoning this for now.

**Comment by insomniacslk** [comment]
The code looks good to me. As discussed offline, let's make two distinct PRs for the removal of deprecated code, and for the interface change. Same thing for #181 , and also do v4 and v6 changes in one PR. In other words:
* one PR to remove deprecated functions from v4 and v6 code
* one PR with the breaking interface change in v4 and v6 code

**Comment by pmazzini** [comment]
I will remove the deprecated functions in this PR and will focus on the interface change in PR #181.

**Comment by insomniacslk** [comment]
can you also remove the DHCPv6 deprecated functions here?

**Comment by pmazzini** [comment]
> can you also remove the DHCPv6 deprecated functions here?

There are not v6 deprecated functions that I am aware of.

**Comment by insomniacslk** [comment]
sorry, my bad memory, I thought there were also deprecated functions in v6

**Pull request merged**
