### PR TITLE
interfaces: added package with interface facilities

### PR DESCRIPTION
**Pull request by insomniacslk**
There are several places that may benefit from a package with interface facilities, see  https://github.com/systemboot/systemboot/pull/73 for context

### CODE REVIEW

**Comment by pmazzini** [comment]
The same changes will need to be applied to `dhcpv4/server_test.go`: https://github.com/insomniacslk/dhcp/blob/master/dhcpv4/server_test.go#L96

**Comment by insomniacslk** [comment]
> The same changes will need to be applied to `dhcpv4/server_test.go`: https://github.com/insomniacslk/dhcp/blob/master/dhcpv4/server_test.go#L96

silly me, I didn't add it to the commit. Added now

**Comment by pmazzini** [comment]
Should the `README.md` also be updated if a new package is added?

**Comment by insomniacslk** [comment]
> Should the `README.md` also be updated if a new package is added?

Done

**Pull request merged**
