### PR TITLE
remove unix rand for urand

### PR DESCRIPTION
**Pull request by isi-lincoln**

### CODE REVIEW

**Comment by isi-lincoln** [comment]
sorry meant to do this to my fork.

**Comment by insomniacslk** [comment]
@isi-lincoln , do you have changes that you plan to upstream from your fork?

**Comment by isi-lincoln** [comment]
not at the moment. again apologies for selecting the wrong branch to PR.

**Comment by insomniacslk** [comment]
that's no problem. If there's anything that you would like to see in this library don't hesitate to open issues or send PRs! Better here than in forks :)

**Pull request closed without merging**
