### PR TITLE
Proposed removal of some logging from Serve() function

### PR DESCRIPTION
**Pull request by kworm83**
I propose that the stdout logging at startup, before error return, and on each connection should be removed from the Serve() function.  Since it is a library logging does not seem appropriate in those areas.  I left the logging in the two areas that continue instead of error return for discussion on whether it would be appropriate to remove those and just silently drop packets/connections with errors.

### CODE REVIEW

**Comment by pmazzini** [comment]
Go’s log package doesn’t have leveled logs which would help disabling it. It makes sense not to log in the library. I don't have a strong opinion with regard to this change. @insomniacslk?

**Comment by hugelgupf** [comment]
we could do something like in nclient4?

**Comment by pmazzini** [comment]
> we could do something like in nclient4?

Yes, that is probably the best approach.

**Comment by pmazzini** [comment]
Closing in favor of #371

**Pull request closed without merging**
