### PR TITLE
dhcpv6: rename stuttering types.

### PR DESCRIPTION
**Pull request by hugelgupf**
dhcpv6.DHCPv6Message -> dhcpv6.Message
dhcpv6.DHCPv6Relay   -> dhcpv6.RelayMessage

### CODE REVIEW

**Comment by pmazzini** [comment]
After fixing the lint warning it LGTM.

**Comment by hugelgupf** [comment]
I fixed all the stickler warnings... I'm not sure what it wants from me now...

**Comment by hugelgupf** [comment]
Argh, fixed it.

**Comment by hugelgupf** [comment]
Combining with #253, so that there can be only one rtr7 PR.

**Pull request closed without merging**
