### PR TITLE
Added OptGenericIP to simplify creation of options that wrap an IP address

### PR DESCRIPTION
**Pull request by insomniacslk**
OptGenericIP is a fake option that simplifies the creation of other options that wrap an IP address.

### CODE REVIEW

**Comment by insomniacslk** [comment]
@get9 this is how a generic IP option could look like (https://github.com/insomniacslk/dhcp/pull/18 for background). Do you think it's worth doing?

**Comment by insomniacslk** [comment]
Another disadvantage of this approach is that the field would always be named `IP`, not `BroadcastAddress`

**Comment by insomniacslk** [comment]
it would also require exposing this piece of internals to the caller (e.g. `RequestFromOffer` in `dhcp4.go`). Even less sure if I like this or not

**Comment by get9** [comment]
What if instead we make OptGenericIP look like the following:
```
type OptGenericIP struct {
    name string
    code OptionCode
    IP net.IP
}
```

and then you create one like:
```
newOpt := OptGenericIP{
    name: "BroadcastAddress",
    code: OptionBroadcastAddress,
    IP: myCoolIP,
}
```

Then the `ToString()` looks something like:
```
func (o *OptGenericIP) ToString() string {
    return fmt.Sprintf("%s -> %v", o.name, o.IP)
}
```

This way we can fully parameterize the option, but still share the implementation since it's _exactly_ the same for all of these options.

Alternatively, we could just copypasta the implementations and switch out names, maybe use codegen or something?

**Comment by insomniacslk** [comment]
in that case you would miss the type checking because there will not be a specialized type for the various IP-based options. I think we'd rather copy-pasta until all the options are implemented :(

**Comment by nemith** [comment]
May be able to accomplish this with embedding instead.

**Comment by insomniacslk** [comment]
that was the idea - https://github.com/insomniacslk/dhcp/pull/19/files#diff-530d8bda11b58b48549f7b6391d40041R10 . Is that what you mean?

**Comment by insomniacslk** [comment]
closing this because the pros are less than the cons

**Pull request closed without merging**
